// Copyright 2023–2025 Skip
import SwiftUI

struct IconPlayground: View {
    var body: some View {
        ScrollView {
            LazyVStack(spacing: 16) {
                ForEach(Array(iconNames.enumerated()), id: \.offset) { iconIndexName in
                    iconRow(iconIndexName.element, index: iconIndexName.offset)
                }
            }
            .padding()
        }
        .toolbar {
            PlaygroundSourceLink(file: "IconPlayground.swift")
        }
    }

    func iconRow(_ imageName: String, index: Int) -> some View {
        HStack {
            Text(imageName)
            Spacer()
            Image(imageName, bundle: .module)
                .resizable()
                .aspectRatio(contentMode: .fit)
                .foregroundStyle(iconColors[index % iconColors.count])
                .frame(width: 30, height: 30)
        }
    }
}

private let iconColors = [Color.blue, Color.red, Color.green, Color.yellow, Color.orange, Color.brown, Color.cyan, Color.indigo, Color.mint, Color.yellow, Color.pink, Color.purple, Color.teal]

fileprivate let iconNames: [String] = [
    "accessibility",
    "add-circle",
    "add",
    "airplane",
    "alarm",
    "albums",
    "alert-circle",
    "alert",
    "american-football",
    "analytics",
    "aperture",
    "apps",
    "archive",
    "at-circle",
    "at",
    "bar-chart",
    "barbell",
    "barcode",
    "baseball",
    "basket",
    "basketball",
    "battery-charging",
    "battery-dead",
    "battery-full",
    "battery-half",
    "beaker",
    "bed",
    "beer",
    "bicycle",
    "binoculars",
    "bluetooth",
    "boat",
    "body",
    "bonfire",
    "book",
    "bookmark",
    "bookmarks",
    "bowling-ball",
    "briefcase",
    "browsers",
    "brush",
    "bug",
    "build",
    "bulb",
    "bus",
    "business",
    "cafe",
    "calculator",
    "calendar-number",
    "calendar",
    "call",
    "camera-reverse",
    "camera",
    "car-sport",
    "car",
    "card",
    "cart",
    "cash",
    "cellular",
    "clipboard",
    "close-circle",
    "close",
    "cloud-circle",
    "cloud-done",
    "cloud-download",
    "cloud-offline",
    "cloud-upload",
    "cloud",
    "cloudy-night",
    "cloudy",
    "code-download",
    "code-slash",
    "code-working",
    "code",
    "cog",
    "copy",
    "create",
    "crop",
    "cube",
    "cut",
    "desktop",
    "diamond",
    "dice",
    "disc",
    "game-controller",
    "gift",
    "glasses",
    "globe",
    "golf",
    "grid",
    "hammer",
    "layers",
    "leaf",
    "library",
    "link",
    "list-circle",
    "list",
    "locate",
    "location",
    "lock-closed",
    "lock-open",
    "log-in",
    "log-out",
    "logo-android",
    "magnet",
    "mail-open",
    "mail-unread",
    "mail",
    "male-female",
    "male",
    "man",
    "map",
    "medal",
    "medical",
    "medkit",
    "megaphone",
    "menu",
    "mic-circle",
    "mic-off-circle",
    "mic-off",
    "mic",
    "moon",
    "move",
    "musical-note",
    "musical-notes",
    "navigate-circle",
    "navigate",
    "newspaper",
    "notifications-circle",
    "notifications-off-circle",
    "notifications-off",
    "notifications",
    "nuclear",
    "nutrition",
    "open",
    "options",
    "print",
    "prism",
    "pulse",
    "push",
    "qr-code",
    "radio-button-off",
    "radio-button-on",
    "radio",
    "rainy",
    "reader",
    "receipt",
    "recording",
    "refresh-circle",
    "refresh",
    "reload-circle",
    "reload",
    "remove-circle",
    "remove",
    "repeat",
    "resize",
    "restaurant",
    "ribbon",
    "rocket",
    "rose",
    "sad",
    "save",
    "scale",
    "scan-circle",
    "scan",
    "school",
    "search-circle",
    "search",
    "send",
    "swap-horizontal",
    "swap-vertical",
    "sync-circle",
    "sync",
    "telescope",
    "tennisball",
    "terminal",
    "text",
    "thermometer",
    "thumbs-down",
    "thumbs-up",
    "thunderstorm",
    "ticket",
    "time",
    "triangle",
    "trophy",
    "tv",
    "umbrella",
    "unlink",
    "walk",
    "wallet",
    "warning",
    "watch",
    "water",
    "wifi",
    "wine",
    "woman",
]

