
copyright "#{Time.now.year} Skip"
#default_language("en-US")

force(true) # Skip HTML report verification
automatic_release(true)
skip_screenshots(false)
precheck_include_in_app_purchases(false)

#skip_binary_upload(true)
#submit_for_review(true)

