# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :release do |options|
  desc "Build and release app"
  # only build the iOS side of the app
  ENV["SKIP_ZERO"] = "true"

  build_app(
    sdk: "iphoneos",
    xcconfig: "fastlane/AppStore.xcconfig",
    output_directory: "../.build/fastlane/Darwin")
  upload_to_app_store(
    api_key_path: "fastlane/apikey.json",
    submission_information: { 
      add_id_info_uses_idfa: false,
      export_compliance_uses_encryption: false
    },
    release_notes: { default: "Fixes and improvements." }
  )
end

