# This file contains the fastlane.tools configuration
# for the Android half of the Skip app.
# You can find the documentation at https://docs.fastlane.tools

# Load the shared Skip.env properties with the app info
require('dotenv')
Dotenv.load '../../Skip.env'

#default_platform(:android)

platform :android do
  desc "Build Skip Android App"
  lane :build do |options|
    build_config = (options[:release] ? "Release" : "Debug")
    build_ios_app(scheme: ENV['PRODUCT_NAME'], configuration: build_config)
  end

  desc "Test Skip Android App"
  lane :test do
    gradle(task: "test")
  end

  desc "Assemble Skip Android App"
  lane :assemble do
    gradle(task: "clean assembleRelease")
    # sh "your_script.sh"
  end

  desc "Deploy Skip Android App to Google Play"
  lane :upload_play_store do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
