# This file contains the fastlane.tools configuration
# for the Android half of the Skip app.
# You can find the documentation at https://docs.fastlane.tools

# Load the shared Skip.env properties with the app info
require('dotenv')
Dotenv.load '../../Skip.env'

default_platform(:android)

# use the Homebrew gradle rather than expecting a local gradlew
gradle_bin = (ENV['HOMEBREW_PREFIX'] ? ENV['HOMEBREW_PREFIX'] : "/opt/homebrew") + "/bin/gradle"

platform :android do
  desc "Build Skip Android App"
  lane :build do |options|
    build_config = (options[:release] ? "Release" : "Debug")
    gradle(
      task: "build${build_config}",
      gradle_path: gradle_bin,
      flags: "--warning-mode none -x lint"
    )
  end

  desc "Test Skip Android App"
  lane :test do
    gradle(
      task: "test",
      gradle_path: gradle_bin
    )
  end

  desc "Assemble Skip Android App"
  lane :assemble do
    gradle(
      task: "assembleRelease",
      gradle_path: gradle_bin,
      flags: "--warning-mode none -x lint"
    )
    # sh "your_script.sh"
  end

  desc "Deploy Skip Android App to Google Play"
  lane :release do
    assemble
    upload_to_play_store
  end
end
